[global]
dt = 0.001
iterations = 15000

[elements]

[[elements.cube]]
n = 2000
seed = 2
a = 1.0

[[elements.msgdebug]]

[[elements.rk4]]

[[elements.shm]]
c=0.0

[[elements.glrender]]
resolution="1080p"
shader="velocity"
