[global]
dt = 0.0002
iterations = 25000

[elements]

[[elements.star]]
mass=1.0
radius=0.2

[[elements.star]]
mass=2.0
radius=0.2

[[elements.star]]
mass=4.0
radius=0.2

[[elements.msgdebug]]

[[elements.impulse]]
fx=5000.0

[[elements.shm]]
c=0.0
k=10.0
mode="particle"

[[elements.rk4]]

[[elements.csvsink]]
resolution="1080p"
shader="velocity"
file="./plots/shm.csv"
