[global]
dt = 0.01
iterations = 2000

[[elements.solar]]
planets=8
asteroids=50
seed=2

[[elements.simple_astro]]
e = 0.1

[[elements.verlet]]


[[elements.glrender]]
resolution="1080p"
shader="velocity"
