default_install_hook_types: [pre-commit, commit-msg, pre-merge-commit, pre-push]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: check-merge-conflict
    -   id: check-case-conflict
    -   id: detect-private-key
    -   id: trailing-whitespace
    -   id: no-commit-to-branch
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1-1
    hooks:
    -   id: shellcheck
-   repo: https://github.com/crate-ci/committed
    rev: v1.1.11
    hooks:
      -   id: committed
-   repo: local
    hooks:
    -   id: cargo-clippy
        name: cargo clippy
        description: Run clippy linter
        entry: cargo clippy -- --deny unused_variables
        language: system
        types: [rust]
        pass_filenames: false
    -   id: cargo-fmt
        name: cargo fmt
        description: Run cargo fmt
        entry: cargo fmt --all -- --check
        language: system
        types: [rust]
        pass_filenames: false
    -   id: cargo-test
        name: cargo test
        description: Run cargo test
        entry: cargo fmt --all -- --check
        language: system
        types: [rust]
        pass_filenames: false
        stages: [pre-push]
    -   id: no-merge-commits
        name: Forbid merge commits
        entry: bash -c 'echo "Merge commits are not allowed! Learn to rebase!"; exit 1'
        language: system
        stages: [pre-merge-commit]
        always_run: true
    -   id: branch_name
        name: Branch Namimg
        description: Ensure consistent branch naming
        entry: branch_name.sh
        language: script
        stages: [pre-push]
        always_run: true
