[workspace]
resolver = "2"
members = [ "astro","physim-core","glrender", "physim_attribute"]

[workspace.package]
authors = ["Joseph Briggs <jhbriggs@gmail.com>"]
license = "MIT"

[profile.release]
debug = true
