[workspace]
resolver = "2"
members = [ "astro","physim-core","glrender", "physim_attribute", "debug"]

[workspace.package]
authors = ["Joseph Briggs <jhbriggs23@gmail.com>"]
license = "MIT"
repository = "https://github.com/jhb123/physim"

[profile.release]
debug = true
