[global]
dt = 0.0001
iterations = 1500

[elements]

[[elements.cube]]
n = 50000
seed = 2
spin = 0.7
mass = 1000.0
centre=[0.7,0.7,0.0]
v=[0.0,-5.0,0.0]
a = 0.5

[[elements.msgdebug]]

[[elements.plummer]]
n = 20000
seed = 4
spin = 0.7
mass = 1000.0
centre=[-0.7,-0.7,0.0]
v=[0.0,5.0,0.0]
a = 0.5


[[elements.astro2]]
theta = 1.4
e = 0.3


[[elements.glrender]]
resolution="1080p"
shader="yellowblue"