[global]
dt = 0.0005
iterations = 10000

[elements]

[[elements.plummer]]
n = 2000
seed = 2
a = 0.5
spin = -0.2
mass = 100.0
centre = [0.4,0.0,0.5]
v = [0.0,-5.0,0.0]


[[elements.plummer]]
n = 2000
seed = 3
a = 0.5
spin = 0.2
mass = 100.0
centre = [-0.4,0.0,0.5]
v = [0.0,5.0,0.0]


[[elements.astro]]
theta = 0.1
e = 0.2


[[elements.glrender]]
resolution="1080p"