[global]
dt = 0.00001
iterations = 1500

[elements]

[[elements.plummer]]
n = 20000
seed = 2
spin = 0.7
mass = 1000.0
centre=[0.5,0.0,0.0]
v=[0.0,-5.0,0.0]
a = 0.5

[[elements.msgdebug]]

[[elements.plummer]]
n = 20000
seed = 4
spin = 0.7
mass = 1000.0
centre=[-0.5,0.0,0.0]
v=[0.0,5.0,0.0]
a = 0.5


[[elements.astro]]
theta = 0.4
e = 0.5


[[elements.glrender]]
resolution="1080p"
shader="velocity"