[global]
dt = 0.0001
iterations = 150

[elements]

[[elements.cube]]
n = 100000
seed = 2
spin = 20
mass = 1.0
centre=[0.0,0.0,0.0]
v=[0.0,-5.0,0.0]
a = 2.0


[[elements.msgdebug]]


[[elements.astro2]]
theta = 1.5
e = 1.0

[[elements.rk4]]


[[elements.glrender]]
resolution="1080p"
shader="yellowblue"
