name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Build & Package (${{ matrix.platform }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - platform: macos
            os: macos-latest
          - platform: linux
            os: ubuntu-latest
          - platform: windows
            os: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build and Package
        shell: bash
        run: |
          bash ./package.sh ${{ matrix.platform }}

      - name: Upload release tarball
        uses: softprops/action-gh-release@v2
        with:
          files: dist/physim-${{ github.ref_name }}-${{ matrix.platform }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
